default: send rec rec2

#tlsrec: tlsrec.o

#tlsrec.o:
	@#@gcc -o tlsrec tlsrec.c -lcrypto -lssl

send: send.o

send.o:

rec: rec.o

rec.0:

rec2: rec2.o

rec2.o:

clean:
	@rm -f send.o send rec.o rec rec2 rec2.o
	@echo Done!
